# Generated by Django 4.2.5 on 2023-11-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pricepredictioninput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepredictioninput',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='pricepredictioninput',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.AddField(
            model_name='pricepredictioninput',
            name='PredictedPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
