# Generated by Django 4.2.5 on 2023-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_pricepredictioninput_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepredictioninput',
            name='Quantity',
            field=models.CharField(max_length=255),
        ),
    ]
